### ISSUE TITLE
Port to Firefox.

### ISSUE THREAD

**Issue by musically-ut** [musically-ut/arXiv-title-fixer#7]
Now that Firefox supports WebExtensions API well enough, port this extension.

**Comment by cipri-tom** [comment]
Yes, please do ! ❤️

**Comment by musically-ut** [comment]
Released an experimental version for Firefox here: https://addons.mozilla.org/en-US/firefox/addon/arxiv-title-fixer/

Could you please test that out (and give it a rating/review)? :)

If it works for you, I'll close this issue.

**Comment by cipri-tom** [comment]
It works ! Thank you very much

**Comment by musically-ut** [comment]
Thanks for the rating!

There still are a few minor things missing (like the browser/page action icon), but I am going to consider this addon as fully released now. :)

Hence, I'll close this issue.

**Comment by cipri-tom** [comment]
I am not sure what you mean by the "browser/page action icon". I don't use the Chrome version.

Can you make it so that when you release a new version, we'll be notified of changes ?
